const mongoose = require('mongoose');

const cardSchema = new mongoose.Schema(
  {
    id: { type: String, default: () => new mongoose.Types.ObjectId().toString() },
    slug: { type: String, default: '' },
    title: { type: String, required: true },
    titleAr: { type: String, default: '' },
    shortDescription: { type: String, default: '' },
    shortDescriptionAr: { type: String, default: '' },
    description: { type: String, default: '' },
    descriptionAr: { type: String, default: '' },
    image: { type: String, required: true },
    images: { type: [String], default: [] },
    features: { type: [String], default: [] },
    featuresAr: { type: [String], default: [] },
    badge: { type: String, default: '' },
    badgeAr: { type: String, default: '' },
  },
  { _id: false }
);

const heroSlideSchema = new mongoose.Schema(
  {
    id: { type: String, default: () => new mongoose.Types.ObjectId().toString() },
    badge: { type: String, default: '' },
    badgeAr: { type: String, default: '' },
    title: { type: String, required: true },
    titleAr: { type: String, default: '' },
    subtitle: { type: String, default: '' },
    subtitleAr: { type: String, default: '' },
    image: { type: String, required: true },
    primaryBtnText: { type: String, default: 'Explore Our Products' },
    primaryBtnTextAr: { type: String, default: 'استكشف منتجاتنا' },
    primaryBtnLink: { type: String, default: 'products' },
    secondaryBtnText: { type: String, default: 'Request a Quote' },
    secondaryBtnTextAr: { type: String, default: 'طلب عرض سعر' },
    secondaryBtnLink: { type: String, default: 'quote' },
  },
  { _id: false }
);

const featurePointSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    titleAr: { type: String, default: '' },
    desc: { type: String, required: true },
    descAr: { type: String, default: '' },
  },
  { _id: false }
);

const brandItemSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    nameAr: { type: String, default: '' },
    slug: { type: String, default: '' },
    image: { type: String, required: true },
  },
  { _id: false }
);

const statItemSchema = new mongoose.Schema(
  {
    value: { type: String, required: true },
    label: { type: String, required: true },
    labelAr: { type: String, default: '' },
  },
  { _id: false }
);

const siteContentSchema = new mongoose.Schema(
  {
    key: {
      type: String,
      required: true,
      unique: true,
      default: 'homepage',
    },
    hero: {
      title: { type: String, default: 'Quality you can certify.\nSupply you can count on.' },
      titleAr: { type: String, default: 'جودة يمكنك توثيقها.\nإمداد يمكنك الاعتماد عليه.' },
      subtitle: {
        type: String,
        default: 'Industrial detergents and disinfectants, engineered to ISO standards — from formulation to production line.',
      },
      subtitleAr: {
        type: String,
        default: 'المنظفات والمطهرات الصناعية، مصممة وفقاً لمعايير الآيزو - من التركيبة إلى خط الإنتاج.',
      },
      image: { type: String, default: '/images/showcase/hero_scientist_clean.png' },
      primaryBtnText: { type: String, default: 'Explore Our Products' },
      primaryBtnTextAr: { type: String, default: 'استكشف منتجاتنا' },
      secondaryBtnText: { type: String, default: 'Request a Quote' },
      secondaryBtnTextAr: { type: String, default: 'طلب عرض سعر' },
    },
    heroSlides: {
      type: [heroSlideSchema],
      default: [
        {
          id: 'slide-1',
          badge: 'Certified Chemical Excellence',
          badgeAr: 'تميز كيميائي معتمد',
          title: 'Quality you can certify.\nSupply you can count on.',
          titleAr: 'جودة يمكنك توثيقها.\nإمداد يمكنك الاعتماد عليه.',
          subtitle: 'Industrial detergents and disinfectants, engineered to ISO standards — from formulation to production line.',
          subtitleAr: 'المنظفات والمطهرات الصناعية، مصممة وفقاً لمعايير الآيزو - من التركيبة إلى خط الإنتاج.',
          image: '/images/showcase/hero_scientist_clean.png',
          primaryBtnText: 'Explore Our Products',
          primaryBtnTextAr: 'استكشف منتجاتنا',
          primaryBtnLink: 'products',
          secondaryBtnText: 'Request a Quote',
          secondaryBtnTextAr: 'طلب عرض سعر',
          secondaryBtnLink: 'quote',
        },
        {
          id: 'slide-2',
          badge: 'Healthcare & Hospital Bio-Security',
          badgeAr: 'الأمان الحيوي للمستشفيات والمنشآت الصحية',
          title: 'Medical-Grade Disinfection.\nMaximum Bio-Security.',
          titleAr: 'تطهير طبي معتمد.\nأعلى درجات الأمان الحيوي.',
          subtitle: 'Certified quaternary and hospital disinfectants trusted by top healthcare facilities and institutions across Egypt.',
          subtitleAr: 'مطهرات كواترناري ومحاليل تعقيم طبية معتمدة تثق بها كبرى المستشفيات والمنشآت الصحية في مصر.',
          image: '/images/categories/hospital.jpg',
          primaryBtnText: 'Institutional Solutions',
          primaryBtnTextAr: 'الحلول المؤسسية',
          primaryBtnLink: 'institutional',
          secondaryBtnText: 'Request Quotation',
          secondaryBtnTextAr: 'طلب تسعير جملة',
          secondaryBtnLink: 'quote',
        },
        {
          id: 'slide-3',
          badge: 'Heavy Industry & Fleet Operations',
          badgeAr: 'الصناعات الثقيلة وأساطيل النقل',
          title: 'Heavy-Duty Chemical Power.\nUncompromising Performance.',
          titleAr: 'قوة كيميائية فائقة للصناعات الشاقة.\nأداء بلا مساومة.',
          subtitle: 'Specialized engine degreasers, high-foam snow car shampoos, and industrial scale removers for heavy operations.',
          subtitleAr: 'مزيلات شحوم المحركات، شامبوهات رغوية فائقة للسيارات، ومذيبات ترسبات صناعية للمصانع والورش الكبرى.',
          image: '/images/categories/car-care.jpg',
          primaryBtnText: 'Explore Heavy Formulations',
          primaryBtnTextAr: 'استكشف المنظفات الشاقة',
          primaryBtnLink: 'products',
          secondaryBtnText: 'Custom Formulation',
          secondaryBtnTextAr: 'طلب عينة خاصة',
          secondaryBtnLink: 'quote',
        },
        {
          id: 'slide-4',
          badge: 'Turnkey Contract Manufacturing',
          badgeAr: 'تصنيع كيميائي وتعبئة لحساب الغير',
          title: 'Your Brand, Powered by\nEssamco Chemical Engineering.',
          titleAr: 'علامتك التجارية بقوة\nالهندسة الكيميائية من عصامكو.',
          subtitle: 'Turnkey private-label manufacturing, custom formulation, ISO-certified bottling, and regulatory licensing support.',
          subtitleAr: 'تصنيع شامل لحساب الغير، تركيبات كيميائية مخصصة، تعبئة بمعايير الآيزو ودعم كامل للتراخيص والمطابقة.',
          image: '/images/showcase/branding_manufacturing.png',
          primaryBtnText: 'Private Label Services',
          primaryBtnTextAr: 'خدمات التصنيع للغير',
          primaryBtnLink: 'private-label',
          secondaryBtnText: 'Partner With Us',
          secondaryBtnTextAr: 'شراكة التصنيع',
          secondaryBtnLink: 'quote',
        },
      ],
    },
    stats: {
      founded: { type: String, default: '1997' },
      foundedLabel: { type: String, default: 'Founded' },
      foundedLabelAr: { type: String, default: 'سنة التأسيس' },
      years: { type: String, default: '+25' },
      yearsLabel: { type: String, default: 'Years' },
      yearsLabelAr: { type: String, default: 'عاماً' },
      categories: { type: String, default: '7' },
      categoriesLabel: { type: String, default: 'Categories' },
      categoriesLabelAr: { type: String, default: 'تصنيفات' },
      metrics: {
        type: [statItemSchema],
        default: [
          { value: '1997', label: 'Founded', labelAr: 'سنة التأسيس' },
          { value: '+25', label: 'Years', labelAr: 'عاماً' },
          { value: '7', label: 'Categories', labelAr: 'تصنيفات' },
        ],
      },
    },
    institutional: {
      title: { type: String, default: 'Institutional Solutions' },
      titleAr: { type: String, default: 'الحلول المؤسسية' },
      subtitle: {
        type: String,
        default: 'Bulk supply, Custom packaging and documentation for schools, hospitals and Industry.',
      },
      subtitleAr: {
        type: String,
        default: 'توريد بالجملة، تعبئة مخصصة وتوثيق للمدارس والمستشفيات والقطاع الصناعي.',
      },
      cards: {
        type: [cardSchema],
        default: [
          {
            id: 'inst-1',
            slug: 'bulk-contracts',
            title: 'Bulk Contracts & Institutional Supply',
            titleAr: 'عقود التوريد والمبيعات المؤسسية',
            shortDescription: 'Long-term bulk supply agreements with flexible scheduling for hospitals, hotels, and industrial plants.',
            shortDescriptionAr: 'اتفاقيات توريد بالجملة مجدولة وموثوقة للمستشفيات، الفنادق، المصانع، والمؤسسات الكبرى.',
            description: 'Essamco provides comprehensive institutional supply contracts designed for high-consumption entities including university hospitals, luxury resort chains, public transport fleets, and industrial manufacturers. We ensure guaranteed supply stability, dedicated account managers, priority batch manufacturing, and customized payment terms with tiered volume discounts.',
            descriptionAr: 'تقدم عصامكو عقود توريد مؤسسية شاملة مصممة خصيصاً للجهات ذات الاستهلاك الضخم مثل المستشفيات الجامعية، سلاسل الفنادق والمنتجعات، أساطيل النقل، والمجمعات الصناعية. نضمن استقرار الإمداد، وإدارة حساب مخصصة، وأولوية في خطوط الإنتاج وجداول تسليم مرنة بأسعار تنافسية مخفضة.',
            image: '/images/showcase/bulk_contracts.png',
            images: [
              '/images/showcase/bulk_contracts.png',
              '/images/facilities/warehouse.jpg',
              '/images/facilities/factory-tanks.jpg',
            ],
            features: [
              'Scheduled monthly and quarterly deliveries',
              'Volume-tiered institutional pricing discounts',
              'Dedicated chemical logistics and fleet transport',
              'Quality assurance batch certificates with every shipment',
            ],
            featuresAr: [
              'تسليمات مجدولة شهرية وربع سنوية تضمن استمرار العمليات',
              'خصومات حجمية وتسهيلات تجارية مخصصة للجهات الكبرى',
              'أسطول شحن وتوزيع كيميائي معتمد وسريع',
              'شهادات فحص ومطابقة مخبرية مرفقة مع كل شحنة',
            ],
            badge: 'High Capacity',
            badgeAr: 'طاقة إنتاجية كبرى',
          },
          {
            id: 'inst-2',
            slug: 'custom-packaging',
            title: 'Custom Packaging & Volume Sizes',
            titleAr: 'التعبئة المخصصة والأحجام المختلفة',
            shortDescription: 'Tailored container formats from 1L retail bottles to 20L canisters, 200L drums and 1000L IBC totes.',
            shortDescriptionAr: 'أحجام وعبوات متعددة تبدأ من عبوات 1 لتر وحتى جراكن 20 لتر، براميل 200 لتر، وخزانات IBC سعة 1000 لتر.',
            description: 'Every facility has unique dispensing and storage requirements. Essamco delivers full packaging customization options tailored to automated dilution stations, industrial workshops, and commercial kitchens. All containers comply with international hazardous materials transport regulations (UN Certified) and feature ergonomic handles and tamper-evident sealing.',
            descriptionAr: 'تختلف متطلبات التخزين والاستخدام من منشأة لأخرى. لذلك توفر عصامكو خيارات تعبئة مرنة متوافقة مع محطات التخفيف الآلية، الورش الصناعية، والمطابخ التجارية. جميع العبوات مطابقة للمواصفات القياسية لنقل المواد الكيميائية مع أغطية محكمة وأمان كامل.',
            image: '/images/showcase/custom_packaging.png',
            images: [
              '/images/showcase/custom_packaging.png',
              '/images/facilities/factory-tanks.jpg',
              '/images/facilities/warehouse.jpg',
            ],
            features: [
              'Heavy-duty HDPE containers resistant to chemical degradation',
              'Bilingual labeling with clear dilution charts & pictograms',
              'Tamper-evident vented caps for safe transport and storage',
              'Compatible with automatic commercial wall-mounted dosing dispensers',
            ],
            featuresAr: [
              'عبوات بولي إيثيلين HDPE عالية الكثافة ومقاومة للتآكل الكيميائي',
              'ملصقات ثنائية اللغة ببيانات واضحة ونسب التخفيف الموصى بها',
              'أغطية أمان بصمام تنفيس لضمان سلامة النقل والتخزين',
              'متوافقة مع محطات الخلط والتوزيع الجدارية الآلية',
            ],
            badge: 'Flexible Sizes',
            badgeAr: 'أحجام مرنة',
          },
          {
            id: 'inst-3',
            slug: 'safety-sheets',
            title: 'Safety Data Sheets (MSDS) & ISO Certifications',
            titleAr: 'صحائف بيانات السلامة (MSDS) وتوثيق الآيزو',
            shortDescription: 'Full technical documentation, MoH registrations, and GHS-compliant Material Safety Data Sheets.',
            shortDescriptionAr: 'ملفات فنية كاملة، اعتمادات وزارة الصحة، وصحائف بيانات سلامة المواد المتوافقة مع النظام العالمي المتوافق (GHS).',
            description: 'Institutional compliance requires rigorous documentation. Essamco equips all corporate clients with accredited Material Safety Data Sheets (MSDS), certificates of analysis (CoA) for each production batch, official Ministry of Health registration documents, and ISO 9001, ISO 14001, and ISO 45001 verification for hospital accreditation and environmental audits.',
            descriptionAr: 'تتطلب معايير الجودة والرقابة المؤسسية توثيقاً صارماً. توفر عصامكو لكافة عملائها ملفات بيانات سلامة المواد (MSDS) المعتمدة، وشهادات التحليل المخبري (CoA) لكل تشغيلة، واعتمادات وزارة الصحة المصرية، وشهادات الآيزو (ISO 9001, ISO 14001, ISO 45001) لتلبية متطلبات الاعتماد الطبي والبيئي.',
            image: '/images/showcase/safety_sheets.png',
            images: [
              '/images/showcase/safety_sheets.png',
              '/images/facilities/lab-beakers.jpg',
              '/images/facilities/lab-scientist.jpg',
            ],
            features: [
              'Standard 16-section GHS Material Safety Data Sheets (MSDS)',
              'Accredited ISO 9001:2015, ISO 14001:2015, ISO 45001:2018 audit trails',
              'Egyptian Ministry of Health official biocidal registrations',
              'Dedicated chemical safety training seminars for your housekeeping teams',
            ],
            featuresAr: [
              'صحائف بيانات سلامة المواد GHS MSDS القياسية المكونة من 16 قسماً',
              'شهادات آيزو موثقة: ISO 9001، ISO 14001، ISO 45001',
              'تسجيلات وتراخيص وزارة الصحة المصرية للمطهرات والمبيدات الحيوية',
              'دورات تدريبية متخصصة لفرق العمل على الاستخدام الآمن والتخفيف',
            ],
            badge: 'Certified',
            badgeAr: 'معتمد رسمياً',
          },
        ],
      },
    },
    privateLabel: {
      title: { type: String, default: 'Private Label' },
      titleAr: { type: String, default: 'التصنيع للغير' },
      subtitle: {
        type: String,
        default: 'From formulation to final packaging, we bring the same manufacturing standards to your private label line.',
      },
      subtitleAr: {
        type: String,
        default: 'من التركيبة وحتى التغليف النهائي، نقدم نفس معايير التصنيع لخط إنتاجك الخاص.',
      },
      cards: {
        type: [cardSchema],
        default: [
          {
            id: 'pl-1',
            slug: 'custom-formulation',
            title: 'Custom Chemical Formulation & R&D',
            titleAr: 'تطوير وابتكار التركيبات الكيميائية المخصصة',
            shortDescription: 'Proprietary chemical engineering, fragrance matching, viscosity tuning, and active ingredient optimization.',
            shortDescriptionAr: 'هندسة كيميائية متقدمة، مطابقة العطور، ضبط درجات اللزوجة وتركيز المواد الفعالة بدقة.',
            description: 'Our in-house laboratory chemists work with your brand to formulate bespoke chemical cleaning, detailing, and disinfection products that outperform market benchmarks. From pH-neutral car snow foams to ultra-concentrated textile detergents and hospital biocides, we adjust active matter concentrations, color aesthetics, viscosity, and fragrance profiles.',
            descriptionAr: 'يعمل فريق الكيميائيين في مختبرات عصامكو المتطورة جنباً إلى جنب مع علامتك التجارية لتطوير تركيبات كيميائية ومنظفات فريدة تفوق المنتجات المنافسة. من شامبوهات السيارات ذات الرغوة الثلجية، إلى مساحيق وسوائل الغسيل فائقة التركيز والمطهرات، نضبط تركيز المادة الفعالة، واللون، واللزوجة، والعطر بدقة متناهية.',
            image: '/images/showcase/custom_formulation.png',
            images: [
              '/images/showcase/custom_formulation.png',
              '/images/facilities/lab-beakers.jpg',
              '/images/facilities/lab-scientist.jpg',
            ],
            features: [
              'Full analytical laboratory with spectrophotometry and titration testing',
              'Proprietary active ingredient formulation tailored to target price points',
              'Accelerated stability, temperature, and shelf-life testing',
              'Complete intellectual property protection & non-disclosure agreements (NDA)',
            ],
            featuresAr: [
              'مختبر تحليلي مجهز بأحدث أجهزة قياس الطيف والمعايرة الدقيقة',
              'تركيبات حصرية مطورة لتلائم الفئة السعرية المستهدفة لعلامتك',
              'اختبارات الثبات المتسارع وفترات الصلاحية وتحمل درجات الحرارة',
              'حماية كاملة للملكية الفكرية واتفاقيات سرية المعلومات (NDA)',
            ],
            badge: 'R&D Lab',
            badgeAr: 'مختبر أبحاث',
          },
          {
            id: 'pl-2',
            slug: 'branding-manufacturing',
            title: 'Your Branding, Our World-Class Manufacturing',
            titleAr: 'علامتك التجارية وهندستنا الصناعية المتطورة',
            shortDescription: 'Complete end-to-end OEM production: bottle design, professional labelling, and automated packaging.',
            shortDescriptionAr: 'تصنيع شامل من الألف إلى الياء: تصميم القوالب، طباعة الملصقات، وتعبئة وتغليف آلي.',
            description: 'Bring your product vision to life with Essamco contract manufacturing infrastructure. We handle raw material sourcing, automated blending in pharmaceutical-grade stainless steel reactors, precision bottle filling, induction foil sealing, batch lot code inkjet printing, and carton packing under your brand identity.',
            descriptionAr: 'حول فكرة منتجك إلى واقع ملموس مع البنية الصناعية الضخمة لعصامكو. نتولى استيراد المواد الخام النقية، والخلط الآلي في مفاعلات ستانلس ستيل مطابقة للمواصفات، والتعبئة الدقيقة، واللحام الحراري، وطباعة أرقام التشغيلات وتواريخ الصلاحية، والتغليف بالكرتون تحت هويتك التجارية.',
            image: '/images/showcase/branding_manufacturing.png',
            images: [
              '/images/showcase/branding_manufacturing.png',
              '/images/facilities/factory-tanks.jpg',
              '/images/facilities/warehouse.jpg',
            ],
            features: [
              'High-speed automated bottling and labeling lines',
              'Capacity exceeding 50+ metric tons of chemical formulations daily',
              'Strict multi-stage batch quality control inspections',
              'Turnkey delivery directly to your central distribution warehouses',
            ],
            featuresAr: [
              'خطوط تعبئة وتوسيم آلية عالية السرعة والدقة',
              'طاقة إنتاجية تتجاوز 50 طناً يومياً تلبي أكبر الطلبيات',
              'فحص ومراقبة جودة متعدد المراحل لكل دفعة إنتاج',
              'تسليم جاهز ومباشر لمستودعات التوزيع المركزية الخاصة بك',
            ],
            badge: 'Turnkey OEM',
            badgeAr: 'تصنيع متكامل',
          },
          {
            id: 'pl-3',
            slug: 'min-order-quantities',
            title: 'Flexible Minimum Order Quantities (MOQs)',
            titleAr: 'كميات طلب مرنة لدعم الشركات الناشئة والنمو',
            shortDescription: 'Scalable batch volumes enabling new brands to launch efficiently and expand progressively.',
            shortDescriptionAr: 'دفعات إنتاج مرنة تمكن العلامات الجديدة من الانطلاق وتتيح للشركات القائمة التوسع بسلاسة.',
            description: 'We believe in fostering entrepreneurship and agile brand development. Unlike rigid contract manufacturers demanding massive upfront commitments, Essamco provides tiered minimum order quantities (MOQs) allowing startup brands to test market demand, refine branding, and scale production seamlessly as retail distribution grows.',
            descriptionAr: 'نؤمن بدعم رواد الأعمال وتوسيع العلامات التجارية الطموحة. على عكس المصانع التي تفرض كميات مبدئية تعجيزية، توفر عصامكو كميات دنيا مرنة للطلبيات (MOQs) تتيح للعلامات الجديدة اختبار السوق والتوسع التدريجي بما يتناسب مع خطتها التسويقية وشبكة توزيعها.',
            image: '/images/showcase/min_order_quantities.png',
            images: [
              '/images/showcase/min_order_quantities.png',
              '/images/facilities/warehouse.jpg',
              '/images/showcase/bulk_contracts.png',
            ],
            features: [
              'Accessible entry tier order volumes for initial product launches',
              'Fast re-order turnaround times to prevent stock-outs',
              'Scale-up path with progressively lower unit costs as volume rises',
              'Comprehensive guidance on regulatory registration and consumer packaging',
            ],
            featuresAr: [
              'كميات بداية ميسرة لاختبار السوق وإطلاق المنتجات الأولى',
              'سرعة عالية في إعادة الإنتاج والتوريد لتجنب نفاد المخزون',
              'تدرج في انخفاض تكلفة الوحدة مع زيادة أحجام الطلبيات',
              'استشارات قانونية وفنية لتسجيل المنتجات والحصول على التراخيص',
            ],
            badge: 'Agile Scale',
            badgeAr: 'مرونة كاملة',
          },
        ],
      },
    },
    retail: {
      title: { type: String, default: 'Retail Products' },
      titleAr: { type: String, default: 'منتجات التجزئة' },
      subtitle: {
        type: String,
        default: 'Everyday categories for home, laundry, surfaces and more.',
      },
      subtitleAr: {
        type: String,
        default: 'فئات يومية للمنزل والعناية بالملابس والأسطح والمزيد.',
      },
      btnText: { type: String, default: 'Explore Our Products' },
      btnTextAr: { type: String, default: 'استكشف منتجاتنا' },
      cards: {
        type: [cardSchema],
        default: [
          {
            id: 'ret-1',
            slug: 'retail-laundry',
            title: 'Laundry Care & Fabric Softeners',
            titleAr: 'العناية بالغسيل والملابس',
            shortDescription: 'High-efficiency liquid detergents, delicate fabric washes, and long-lasting freshness.',
            shortDescriptionAr: 'سوائل غسيل فائقة الفعالية، غسول للملابس الحساسة، وانتعاش عطري يدوم طويلاً.',
            description: 'Essamco retail laundry formulations are engineered with deep-penetrating enzymes that dissolve tough food, grease, and perspiration stains in both warm and cold water cycles. Formulated with fabric protection polymers and luxurious scents, they preserve fabric colors and softness through repeated washes.',
            descriptionAr: 'صُممت منظفات الغسيل من عصامكو بإنزيمات حيوية متطورة تخترق أصعب بقع الزيوت والأطعمة والعرق في درجات الحرارة الباردة والساخنة. معززة بمركبات حماية الألياف لمنع بهتان الألوان، ومضاف إليها عطور منعشة تدوم طويلاً.',
            image: '/images/showcase/retail_laundry_hd.png',
            images: [
              '/images/showcase/retail_laundry_hd.png',
              '/images/products/laundry-detergent.jpg',
            ],
            features: [
              'Multi-enzyme stain lifting technology',
              'Color-safe and optical brightening agents',
              'Gentle on skin and dermatologist-tested',
              'Concentrated formula requiring lower dosage per load',
            ],
            featuresAr: [
              'تقنية الإنزيمات المتعددة لتفكيك البقع الصعبة',
              'مواد تعزيز الألوان وحماية الأنسجة من التلف',
              'لطيف على البشرة ومختبر جلدياً لسلامة الاستخدام',
              'تركيبة مركزة توفر عدداً أكبر من الغسلات لكل عبوة',
            ],
            badge: 'Consumer Favorite',
            badgeAr: 'الأكثر طلباً',
          },
          {
            id: 'ret-2',
            slug: 'retail-surface',
            title: 'Surface Care & Multi-Purpose Cleaners',
            titleAr: 'العناية بالأسطح والأرضيات',
            shortDescription: 'Streak-free glass cleaners, marble safe floor cleaners, and kitchen degreasers.',
            shortDescriptionAr: 'منظفات زجاج خالية من الآثار، ملمعات أرضيات آمنة للرخام، ومذيبات دهون للمطابخ.',
            description: 'Keep residential and commercial surfaces spotless with Essamco consumer surface care. Engineered with streak-free drying technology, our floor and surface cleaners lift dust, grime, and grease while leaving a protective anti-static layer and an invigorating citrus or lavender aroma.',
            descriptionAr: 'حافظ على نظافة ولمعان كافة الأسطح المنزلية والمكتبية مع مجموعة عصامكو للعناية بالأسطح. توفر تقنية الجفاف السريع لمعاناً نقياً دون أي أثر أو خطوط، مع تكوين طبقة مضادة للأتربة ورائحة عطرية فواحة تدوم ساعات.',
            image: '/images/showcase/retail_surface_hd.png',
            images: [
              '/images/showcase/retail_surface_hd.png',
              '/images/products/glass-cleaner.jpg',
              '/images/products/descaler.jpg',
            ],
            features: [
              'Streak-free rapid drying formulation',
              'Neutral pH safe for marble, ceramic, porcelain, and wood',
              'Fast-acting grease dissolution in kitchens',
              'Infused with long-lasting European essential fragrance oils',
            ],
            featuresAr: [
              'تركيبة سريعة الجفاف تمنع ظهور أي آثار أو بهتان',
              'رقم هيدروجيني معتدل آمن تماماً للرخام، البورسلين، السيراميك، والباركيه',
              'مذيب دهون سريع الفعالية للمطابخ والأفران والشفاطات',
              'معطر بزيوت عطرية أوروبية فاخرة تدوم طويلاً',
            ],
            badge: 'Quick Shine',
            badgeAr: 'لمعان فوري',
          },
          {
            id: 'ret-3',
            slug: 'retail-disinfection',
            title: 'Disinfection & Family Hygiene',
            titleAr: 'التطهير والتعقيم المنزلي',
            shortDescription: 'Kills 99.9% of bacteria and viruses, sanitizing kitchen counters, bathrooms, and play areas.',
            shortDescriptionAr: 'يقضي على 99.9% من الجراثيم والفيروسات، لتعقيم المطابخ، الحمامات، ومناطق الأطفال بأمان.',
            description: 'Providing everyday germ protection, our consumer disinfection range combines high antimicrobial efficacy with safe household handling. Free from harsh noxious fumes, our disinfectants sanitize high-touch surfaces, bathrooms, and food preparation areas reliably.',
            descriptionAr: 'توفر مجموعة التطهير المنزلي حماية يومية متكاملة ضد الجراثيم والفيروسات مع أعلى معايير الأمان للأسرة. تركيبات خالية من الروائح الخانقة أو المواد المبيضة الضارة، مثالية لتعقيم مقابض الأبواب، والحمامات، ومناطق إعداد الطعام.',
            image: '/images/showcase/retail_disinfection_hd.png',
            images: [
              '/images/showcase/retail_disinfection_hd.png',
              '/images/products/disinfectant-jerrycan.jpg',
              '/images/products/hand-soap.jpg',
            ],
            features: [
              'Tested kill-rate of 99.9% against bacteria, fungi, and enveloped viruses',
              'Bleach-free and non-corrosive to common household metals',
              'Deodorizes at the molecular level eliminating foul odors',
              'Child-resistant safety closure packaging',
            ],
            featuresAr: [
              'فعالية مختبرة تقضي على 99.9% من البكتيريا والفطريات والفيروسات',
              'خالٍ من الكلور والمواد الكاوية وآمن على الأسطح المعدنية',
              'يقضي على مسببات الروائح الكريهة من مصدرها',
              'عبوات مزودة بأغطية أمان لحماية الأطفال',
            ],
            badge: '99.9% Kill',
            badgeAr: 'حماية 99.9%',
          },
          {
            id: 'ret-4',
            slug: 'retail-soap-noodles',
            title: 'Soap Noodles & Semi-Finished Raw Materials',
            titleAr: 'معكرونة الصابون والمنتجات نصف المصنعة',
            shortDescription: 'Premium vegetable-based soap noodles 80/20 and 70/30 for soap manufacturers and artisans.',
            shortDescriptionAr: 'رقائق ومعكرونة صابون نباتي نقي 80/20 و70/30 لمصنعي الصابون وورش الإنتاج.',
            description: 'For industrial and artisan soap manufacturers, Essamco supplies high-grade pure vegetable soap noodles derived from refined palm and coconut oils. With excellent foamability, smooth extrudability, high whiteness, and optimal moisture content, our soap bases ensure premium bar soap production.',
            descriptionAr: 'لمصنعي الصابون التجاري واليدوي، توفر عصامكو أجود أنواع معكرونة ورقائق الصابون المشتقة من زيوت نباتية نقية (نخيل وجوز هند). تتميز بقابلية فائقة للرغوة والتشكيل، ولون ناصع، ومحتوى رطوبة متوازن يضمن إنتاج صابون فاخر ومتماسك.',
            image: '/images/showcase/retail_soap_noodles_hd.png',
            images: [
              '/images/showcase/retail_soap_noodles_hd.png',
              '/images/facilities/factory-tanks.jpg',
            ],
            features: [
              '100% vegetable oil derived (non-animal fat basis)',
              'Standard 80/20 and 70/30 Total Fatty Matter (TFM) grades',
              'High fragrance retention and smooth skin moisturization',
              'Packaged in 25kg multi-wall moisture-barrier paper bags',
            ],
            featuresAr: [
              'مشتق بنسبة 100% من زيوت نباتية نقية خالية من الشحوم الحيوانية',
              'درجات نقاء ومادة دهنية TFM قياسية 80/20 و70/30',
              'قدرة عالية على امتصاص وتثبيت العطور مع نعومة فائقة للبشرة',
              'معبأ في أكياس عازلة للرطوبة متعددة الطبقات سعة 25 كجم',
            ],
            badge: 'Raw Material',
            badgeAr: 'مواد خام نقية',
          },
        ],
      },
    },
    whyChooseUs: {
      title: { type: String, default: 'Why Choose Us' },
      titleAr: { type: String, default: 'لماذا تختارنا' },
      subtitle: { type: String, default: 'Built to Deliver More Than Just Products' },
      subtitleAr: { type: String, default: 'صُممنا لنقدم أكثر من مجرد منتجات' },
      image: { type: String, default: '/images/showcase/why_us_scientist_hd.png' },
      btnText: { type: String, default: 'Request a Quote' },
      btnTextAr: { type: String, default: 'طلب عرض سعر' },
      points: {
        type: [featurePointSchema],
        default: [
          {
            title: '25+ Years of Experience',
            titleAr: '+25 عاماً من الخبرة',
            desc: 'Decades of hands-on expertise in chemical manufacturing, continuously evolving with the needs of our partners.',
            descAr: 'عقود من الخبرة العملية في التصنيع الكيميائي، تتطور باستمرار مع احتياجات شركائنا.',
          },
          {
            title: 'Certified Quality Systems',
            titleAr: 'أنظمة جودة معتمدة',
            desc: 'Our quality, environmental, and occupational health & safety systems are certified to ISO 9001, ISO 14001, and ISO 45001.',
            descAr: 'أنظمة إدارة الجودة والبيئة والسلامة والصحة المهنية معتمدة لشهادات ISO 9001 و ISO 14001 و ISO 45001.',
          },
          {
            title: 'Full Manufacturing Control',
            titleAr: 'تحكم كامل بالتصنيع',
            desc: 'From raw material testing and formulation to production and final quality control, we maintain control across the entire process.',
            descAr: 'من فحص المواد الخام وصياغة التركيبات وحتى الإنتاج ومراقبة الجودة النهائية، نتحكم بكامل مراحل العملية.',
          },
          {
            title: 'Reliable Partnership',
            titleAr: 'شراكة موثوقة ومستدامة',
            desc: 'Consistent quality, transparent pricing, and on-time delivery — the foundations our partners have relied on since 1997.',
            descAr: 'جودة ثابتة، أسعار شفافة وتسليم في المواعيد المحددة - الركائز الأساسية التي يعتمد عليها عملاؤنا منذ عام 1997.',
          },
        ],
      },
    },
    brands: {
      type: [brandItemSchema],
      default: [
        {
          name: 'Brillant',
          nameAr: 'بريلانت',
          slug: 'brillant',
          image: '/images/showcase/brand_brillant_clean.png',
        },
        {
          name: 'Savon',
          nameAr: 'صافون',
          slug: 'savon',
          image: '/images/showcase/brand_savon_clean.png',
        },
        {
          name: 'whiff',
          nameAr: 'ويف',
          slug: 'whiff',
          image: '/images/showcase/brand_whiff_clean.png',
        },
        {
          name: 'Power 3',
          nameAr: 'باور 3',
          slug: 'power-3',
          image: '/images/showcase/brand_power_clean.png',
        },
      ],
    },
    partnershipCta: {
      title: { type: String, default: 'Ready to discuss a supply partnership' },
      titleAr: { type: String, default: 'جاهز لمناقشة شراكة توريد؟' },
      subtitle: { type: String, default: "Have a project in mind? We're ready to help." },
      subtitleAr: { type: String, default: 'هل لديك مشروع أو طلب توريد؟ فريقنا جاهز لمساعدتك.' },
      btnText: { type: String, default: 'Contact Us' },
      btnTextAr: { type: String, default: 'تواصل معنا' },
    },
    footerSettings: {
      tagline: { type: String, default: 'Manufacturing trusted chemical solutions since 1997.' },
      taglineAr: { type: String, default: 'تصنيع حلول كيميائية موثوقة منذ عام 1997.' },
      newsletterTitle: { type: String, default: 'Subscribe to Newsletter' },
      newsletterTitleAr: { type: String, default: 'اشترك في النشرة البريدية' },
      copyright: { type: String, default: '© Copyright 2026, All Rights Reserved by Essamco' },
      copyrightAr: { type: String, default: '© جميع الحقوق محفوظة لشركة عصامكو 2026' },
    },
    socialLinks: {
      facebook: { type: String, default: 'https://facebook.com' },
      twitter: { type: String, default: 'https://twitter.com' },
      linkedin: { type: String, default: 'https://linkedin.com' },
      instagram: { type: String, default: 'https://instagram.com' },
      whatsapp: { type: String, default: '+201000000000' },
      youtube: { type: String, default: '' },
      tiktok: { type: String, default: '' },
    },
    seo: {
      metaTitle: {
        type: String,
        default: 'ESSAMCO | Industrial Detergents & Disinfectants Manufacturer',
      },
      metaTitleAr: {
        type: String,
        default: 'عصامكو | تصنيع المنظفات والمطهرات الصناعية وحلول التطهير',
      },
      metaDescription: {
        type: String,
        default:
          'ESSAMCO is an Egyptian manufacturer of ISO-certified industrial detergents, disinfectants, institutional hygiene solutions, and private label chemicals since 1997.',
      },
      metaDescriptionAr: {
        type: String,
        default:
          'شركة عصامكو لصناعة المنظفات والمطهرات الكيميائية المعتمدة وفقاً لمعايير الآيزو، حلول النظافة المؤسسية والتصنيع للغير منذ عام 1997.',
      },
      keywords: {
        type: String,
        default:
          'industrial detergents, disinfectants, ISO 9001, hospital hygiene, private label manufacturing, Egypt chemicals, bulk cleaning supply',
      },
      keywordsAr: {
        type: String,
        default:
          'منظفات صناعية، مطهرات، شهادة الآيزو، تعقيم مستشفيات، تصنيع للغير، كيماويات مصر، توريد منظفات بالجملة',
      },
      ogImage: {
        type: String,
        default: '/images/showcase/hero_scientist_clean.png',
      },
      canonicalUrl: {
        type: String,
        default: 'https://essamco.com',
      },
      robotsIndex: {
        type: Boolean,
        default: true,
      },
      robotsFollow: {
        type: Boolean,
        default: true,
      },
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('SiteContent', siteContentSchema);
